### ISSUE TITLE
Does this gem support has_one and habtm relationships?

### ISSUE THREAD

**Issue by vraravam** [holyketzer/activeadmin-audit#5]
I have a model that has relationships with others using both `has_one` and `has_and_belongs_to_many` models/tables. I would like to use this gem to get audits in place for the main/parent models. How can i achieve this?

**Comment by holyketzer** [comment]
In model when you want use audit put this:

``` ruby
has_versions also_include: {
  has_many_relations: [:id],
  has_one_relation: [:id],
}
```

**Comment by vraravam** [comment]
@holyketzer - tx, i will try it out immediately. I am also using STI, could you please give me any pointers on this as well?

**Comment by holyketzer** [comment]
As I see there is no special actions required to use it with STI, it should work the same way as without.
